config/urls.py
# Django:
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

# Thirdparty:
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("grab_money.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("base/", include("grab_money.base.urls", namespace="base")),
    path("category/", include("grab_money.category.urls", namespace="category")),
    path(
        "bank_account/",
        include("grab_money.bank_account.urls", namespace="bank_account"),
    ),
    path(
        "transaction/", include("grab_money.transaction.urls", namespace="transaction")
    ),
    path("currency/", include("grab_money.currency.urls", namespace="currency")),
    path(
        "currency_rate/",
        include("grab_money.currency_rate.urls", namespace="currency_rate"),
    ),
    path(
        "money_statistics/",
        include("grab_money.money_statistics.urls", namespace="money_statistics"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

grab_money/base/urls.py
# Django:
from django.urls import path

# Localfolder:
from . import views

app_name = "base"
urlpatterns = [
    path(
        "upload-transaction-file/",
        views.upload_transaction_file,
        name="upload-transaction-file",
    ),
]

grab_money/category/urls.py
# Django:
from django.urls import path

# Localfolder:
from .views import (
    category_create,
    category_delete,
    category_detail,
    category_edit,
    category_list,
)

app_name = "category"
urlpatterns = [
    path("", category_list, name="category-list"),
    path("create/", category_create, name="category-create"),
    path("edit/<int:id>/", category_edit, name="category-edit"),
    path("delete/<int:id>/", category_delete, name="category-delete"),
    path("detail/<int:id>/", category_detail, name="category-detail"),
]

grab_money/transaction/urls.py
# Django:
from django.urls import path

# Localfolder:
from .views import (
    transaction_assign_category,
    transaction_create,
    transaction_delete,
    transaction_detail,
    transaction_edit,
    transaction_list,
    transaction_unknown_list,
)

app_name = "transaction"
urlpatterns = [
    path("", transaction_list, name="transaction-list"),
    path("unknown", transaction_unknown_list, name="transaction-unknown-list"),
    path(
        "assign-category/<int:id>",
        transaction_assign_category,
        name="transaction-assign-category",
    ),
    path("create/", transaction_create, name="transaction-create"),
    path("edit/<int:id>", transaction_edit, name="transaction-edit"),
    path(
        "edit/<int:id>/<int:category_id>",
        transaction_edit,
        name="transaction-edit-with-cat",
    ),
    path("delete/<int:id>", transaction_delete, name="transaction-delete"),
    path("detail/<int:id>", transaction_detail, name="transaction-detail"),
]

grab_money/users/urls.py
# Django:
from django.urls import path

# Firstparty:
from grab_money.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

grab_money/base/models.py
# Django:
from django.db import models

# Create your models here.

grab_money/money_statistics/models.py
# Django:
from django.db import models

# Create your models here.

grab_money/bank_account/forms.py
# Django:
from django import forms
from django.forms import ModelForm
from django.urls import reverse

# Thirdparty:
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# Firstparty:
from grab_money.bank_account.models import BankAccount


# Create the form class.
class BankAccountForm(ModelForm):
    class Meta:
        model = BankAccount
        fields = [
            "name",
            "number_account",
            "number_card",
            "currency",
            "opening_debit",
            "opening_credit",
            "category",
            "type",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "add-new-bank_account"
        self.helper.form_class = "NewBankAccount"
        self.helper.form_method = "post"
        self.helper.form_action = ""
        self.helper.add_input(Submit("submit", "create"))


class EditBankAccountForm(BankAccountForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_action = reverse(
            "bank_account:bank-account-edit", args=[self.instance.id]
        )
        self.helper.inputs[0].value = "save"

grab_money/category/forms.py
# Django:
from django.forms import ModelForm
from django.urls import reverse

# Thirdparty:
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# Localfolder:
from .models import Category


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            "category_name",
            "description",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "category_create"
        self.helper.form_class = "Category"
        self.helper.form_method = "post"
        self.helper.form_action = ""
        self.helper.add_input(Submit("submit", "Save"))


class EditCategoryForm(CategoryForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.id:
            self.helper.form_action = reverse(
                "category:category-edit", args=[self.instance.id]
            )
        else:
            self.helper.form_action = reverse("category-list")
        # self.helper.add_input(Submit("submit", "Save"))
        self.helper.inputs[0].value = "Save"

grab_money/bank_account/views.py
# Django:
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Firstparty:
from grab_money.bank_account.forms import BankAccountForm, EditBankAccountForm
from grab_money.base.views import universal_error

# Localfolder:
from .models import BankAccount


@login_required(login_url="/accounts/login/")
def account_name_list(request):
    bank_accounts = BankAccount.objects.filter(owner=request.user).order_by("id")
    context = {"bank_accounts": bank_accounts}

    return render(request, "bank_account/list.html", context)


@login_required(login_url="/accounts/login/")
def account_name_create(request):

    base_context = {"bank_account_new": BankAccountForm()}
    if request.method == "GET":
        return render(request, "bank_account/list_edit_new.html", base_context)
    elif request.method == "POST":

        form = BankAccountForm(request.POST)
        if form.is_valid():
            bank_account = form.save(commit=False)
            bank_account.owner = request.user
            bank_account.save()
        return HttpResponseRedirect("/bank_account")
    else:
        return universal_error(request, context={"code": 405})


@login_required(login_url="/accounts/login/")
def account_name_delete(request, id):
    bank_account = BankAccount.objects.get(pk=id)

    if request.user != bank_account.owner:
        return universal_error(request, context={"code": 403})
    bank_account.delete()
    return HttpResponseRedirect("/bank_account")


@login_required(login_url="/accounts/login/")
def account_name_edit(request, id):
    bank_account = BankAccount.objects.get(pk=id)
    form = EditBankAccountForm(instance=bank_account)
    if request.method == "GET":
        return render(request, "bank_account/list_edit.html", context={"form": form})
    elif request.method == "POST":
        if request.user != bank_account.owner:
            return universal_error(request, context={"code": 403})

        form = BankAccountForm(request.POST, instance=bank_account)
        if form.is_valid():
            bank_account = form.save(commit=False)
            bank_account.owner = request.user
            bank_account.save()
        return HttpResponseRedirect("/bank_account")
    else:
        return universal_error(request, context={"code": 405})


@login_required(login_url="/accounts/login/")
def account_detail(request, id):
    try:
        account = BankAccount.objects.get(pk=id)
    except BankAccount.DoesNotExist:
        return universal_error(request, context={"code": 404})

    # Check for right request user
    if account.owner != request.user:
        return universal_error(request, context={"code": 403})

    context = {"account": account}
    return render(request, "bank_account/account_detail.html", context)

grab_money/base/views.py
# Django:
from django.shortcuts import redirect, render

# Localfolder:
from .forms import PARSER_MAPPING, UploadTransactionFileForm


def universal_error(request, context=None):
    # if context is none
    if context is None:
        context = {}
        context["title"] = "Unregistered error"
        context["text"] = "Sorry, we have any problems"
    # if you write any specific context["code"] and ["text"]
    elif "text" in context:
        return render(request, "error.html", context)
    # the most usable errors use by context["code"]
    else:
        if context["code"] == 403:
            context["title"] = "Access denied"
            context["text"] = "You do not have permission for this action"
        elif context["code"] == 404:
            context["title"] = "Page is not found"
            context["text"] = "The requested URL was not found on this server"
        elif context["code"] == 405:
            context["title"] = "Not Allowed"
            context[
                "text"
            ] = "An unsupported HTTP method was used to execute the request"
        elif context["code"] == 500:
            context["title"] = "Server Error"
            context["text"] = "Sorry, something went wrong"

    return render(request, "error.html", context)


def upload_transaction_file(request):
    if request.method == "GET":
        context = dict(form=UploadTransactionFileForm())
        return render(request, "base/upload_transaction_file.html", context)
    elif request.method == "POST":
        form = UploadTransactionFileForm(request.POST)
        if "file" in request.FILES:
            file = request.FILES["file"]
            parser = PARSER_MAPPING[form.data["parser"]]()
            transactions_data = parser.parse(file)
            parser.store_transactions(transactions_data, request.user)
            return redirect("transaction:transaction-list")
        else:
            return universal_error(
                request, context={"code": 500, "text": "Couldn't found file"}
            )
    else:
        return universal_error(request, context={"code": 405})

grab_money/category/views.py
# Django:
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

# Firstparty:
from grab_money.base.views import universal_error
from grab_money.transaction.models import Transaction

# Localfolder:
from .forms import CategoryForm, EditCategoryForm
from .models import Category


@login_required(login_url="/accounts/login/")
def category_list(request):
    categories = Category.objects.filter()
    context = {"categories": categories}
    return render(request, "category/list.html", context)


@login_required(login_url="/accounts/login/")
def category_create(request):
    context = {"form": CategoryForm()}
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            new_category = form.save(commit=False)
            new_category.owner = request.user
            new_category.save()
            return redirect("category:category-list")
    elif request.method == "GET":
        return render(request, "category/category_create.html", context)


@login_required(login_url="/accounts/login/")
def category_edit(request, id):
    category = Category.objects.get(pk=id)
    if request.method == "POST":
        if request.user != category.owner:
            return universal_error(request, context={"code": 403})
        form = EditCategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect("category:category-list")
    else:
        if request.user != category.owner:
            return universal_error(request, context={"code": 403})
        form = EditCategoryForm(instance=category)
    return render(request, "category/category_edit.html", {"form": form})


@login_required(login_url="/accounts/login/")
def category_delete(request, id):
    category = Category.objects.get(pk=id)
    if request.user != category.owner:
        return universal_error(request, context={"code": 403})
    category.delete()
    return redirect("category:category-list")


@login_required(login_url="/accounts/login/")
def category_detail(request, id):
    category = Category.objects.get(pk=id)
    transactions = Transaction.objects.filter(category=id)
    context = {"category": category, "transactions": transactions}
    return render(request, "category/category_detail.html", context)

grab_money/currency/views.py
# Django:
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Localfolder:
from .models import Currency


@login_required(login_url="/accounts/login/")
def currency_list(request):
    currencies = Currency.objects.all()
    context = {"currencies": currencies}
    return render(request, "currency/list.html", context)

grab_money/currency_rate/views.py
# Django:
# Stdlib:
import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

# Firstparty:
from grab_money.currency.models import Currency
from grab_money.currency_rate.utils import get_all_currency_rate_date

# Localfolder:
from .forms import CurrencyRateRefreshForm
from .models import CurrencyRate


@login_required(login_url="/accounts/login/")
def currency_rate_list(request, date):

    currencies = Currency.objects.all()
    if date == "today":
        date = datetime.datetime.now().date()
    rates = CurrencyRate.objects.filter(date=date)

    context = {
        "currencies": currencies,
        "rates": rates,
        "date": date,
        "form": CurrencyRateRefreshForm(),
    }

    return render(request, "currency_rate/list.html", context)


@login_required(login_url="/accounts/login/")
def currency_rate_refresh(request):

    if request.method == "POST":
        form = CurrencyRateRefreshForm(request.POST)

        date = form.data["date"]
        rates = get_all_currency_rate_date(date)

        for rate in rates:
            try:
                currency = Currency.objects.get(short_unit_label=rate["abbreviation"])
                if not CurrencyRate.objects.filter(
                    date=date, currency_id=currency
                ).exists():
                    new_rate = CurrencyRate()
                    new_rate.currency_id = currency
                    new_rate.rate = rate["rate"]
                    new_rate.date = date
                    new_rate.scale = rate["scale"]
                    new_rate.save()

            except Currency.DoesNotExist:
                pass

    return redirect("currency_rate:currency-rate-list", date=date)


@login_required(login_url="/accounts/login/")
def currency_rate_detail(request, shortalias):
    currencies = Currency.objects.filter(short_unit_label=shortalias)
    if currencies:
        currency = currencies[0]
        rates = CurrencyRate.objects.filter(currency_id=currency)
        context = {
            "currency": currency,
            "rates": rates,
            "scale": rates and rates[0].scale or False,
        }
        return render(request, "currency_rate/detail.html", context)
    return currency_rate_list(request)

grab_money/templates/transaction/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Transactions {% endblock %}

{% block content %}

  <h3>My transactions</h3>

    <h3> Create </h3>

      {% crispy form form.helper %}


{% endblock %}

grab_money/templates/transaction/delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Transactions {% endblock %}

{% block content %}

  <h3>My transactions</h3>

    <h3> Delete </h3>

{% endblock %}

grab_money/templates/transaction/detail.html
{% extends "base.html" %}

{% block title %} Transaction detail {% endblock %}

{% block content %}

<h3>Transaction details</h3>
<div class="btn-group">
    {% if transaction.owner == user %}
    <a class="btn btn-info" href="{% url 'transaction:transaction-edit' id=transaction.id %}"><i class="fas fa-edit"></i>
        Edit
    </a>
    {% endif %}
    {% if transaction.owner == user %}
    <a class="btn btn-info" href="{% url 'transaction:transaction-delete' id=transaction.id %}" ><i class="fas fa-trash"></i>
        Delete
    </a>
    {% endif %}
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Date</th>
            <th scope="col">Account from</th>
            <th scope="col">Account to</th>
            <th scope="col">Category</th>
            <th scope="col">Amount</th>
            <th scope="col">Description</th>

        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">{{ transaction.id }}</th>
            <td>{{ transaction.date }}</td>
            <td>{{ transaction.account_from }}</td>
            <td>{{ transaction.account_to }}</td>
            <td>{{ transaction.category }}</td>
            <td>{{ transaction.amount }}</td>
            <td>{{ transaction.description }}</td>
        </tr>
    </tbody>
</table>

{% endblock %}

grab_money/templates/transaction/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Transactions {% endblock %}

{% block content %}

  <h3>My transactions</h3>

    <h3> Edit </h3>


      {% crispy form form.helper %}

{% endblock %}

grab_money/templates/transaction/list.html
{% extends "base.html" %}

{% block title %} Transactions {% endblock %}

{% block content %}

  <h3>My transactions
     <a class="btn btn-info" href="{% url 'transaction:transaction-create' %}" ><i class="fas fa-plus aria-hidden='true'" style="margin-right: 10px;"></i>
     Add new
     </a>
     <a class="btn btn-success" href="{% url 'base:upload-transaction-file' %}" ><i class="fas fa-upload aria-hidden='true'" style="margin-right: 10px;"></i>
     Upload Transactions File
     </a>
     <a class="btn btn-warning" href="{% url 'transaction:transaction-unknown-list' %}" ><i class="fas fa-question-circle aria-hidden='true'" style="margin-right: 10px;"></i>
     Unknown Transactions({{ len_unknown_transactions }})
     </a>
   </h3>

    <table id="table_id" class="table table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">Account from</th>
          <th scope="col">Account to</th>
          <th scope="col">Category</th>
          <th scope="col">Amount</th>
          <th scope="col">Description</th>
          <th scope="col">Actions</th>
         </tr>
      </thead>
      <tbody>
        {% for item in transactions %}
		  <tr>
		        <th scope="row">{{ item.id }}</th>
		        <td>{{ item.date }}</td>
		        <td>{{ item.account_from }}</td>
            <td>{{ item.account_to }}</td>
            <td>{{ item.category }}</td>
            <td>{{ item.amount }}</td>
            <td>{{ item.description }}</td>
            <td>
                <a class="btn btn-info" href="{% url 'transaction:transaction-detail' item.id %}" ><i class="fa fa-eye" aria-hidden="true"></i>
                  View
                </a>
                <a class="btn btn-info" href="{% url 'transaction:transaction-edit' item.id %}" ><i class="fas fa-edit"></i>
                  Edit
                </a>
                <a class="btn btn-info" href="{% url 'transaction:transaction-delete' item.id %}"><i class="fas fa-trash"></i>
                  Delete
                </a>
            </td>
      </tr>
        {% endfor %}
      </tbody>
    </table>

    {% block additional_javascript %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/af-2.3.5/b-1.6.2/b-colvis-1.6.2/b-html5-1.6.2/cr-1.5.2/fc-3.3.1/kt-2.5.2/r-2.2.5/rg-1.1.2/rr-1.2.7/sc-2.0.2/sp-1.1.1/datatables.min.css"/>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/af-2.3.5/b-1.6.2/b-colvis-1.6.2/b-html5-1.6.2/cr-1.5.2/fc-3.3.1/kt-2.5.2/r-2.2.5/rg-1.1.2/rr-1.2.7/sc-2.0.2/sp-1.1.1/datatables.min.js"></script>
    <script>
      $(document).ready( function () {
        $('#table_id').DataTable ( {
          dom: 'B<"clear">lfrtip',
          buttons: {
            name: 'primary',
            buttons: ['pdf']
          }}
        );
      });
    </script>
    {% endblock %}

{% endblock %}

grab_money/templates/transaction/unknown_transactions_list.html
{% extends "base.html" %}

{% block title %} Transactions {% endblock %}

{% block content %}

    <h3>Unknown transactions</h3>

    <table id="table_id" class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Date</th>
                <th scope="col">Account from</th>
                <th scope="col">Account to</th>
                <th scope="col">Category</th>
                <th scope="col">Amount</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for item in transactions %}
        <tr>
            <td scope="row">{{ item.id }}</td>
            <td>{{ item.date }}</td>
            <td>{{ item.account_from }}</td>
            <td>{{ item.account_to }}</td>
            <td>
                <form action="{% url 'transaction:transaction-assign-category' item.id %}" method="post">{% csrf_token %}
                    {{ act_form.as_p }}
                    <button type="submit"><i class="fas fa-save"></i></button>
                </form>
            </td>
            <td>{{ item.amount }}</td>
            <td>{{ item.description }}</td>
            <td>
                <a class="btn btn-info" href="{% url 'transaction:transaction-delete' item.id %}">
                    <i class="fas fa-trash"></i>
                    Delete
                </a>
            </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

{% endblock %}