config/urls.py
# Django:
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

# Thirdparty:
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("grab_money.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("base/", include("grab_money.base.urls", namespace="base")),
    path("category/", include("grab_money.category.urls", namespace="category")),
    path(
        "bank_account/",
        include("grab_money.bank_account.urls", namespace="bank_account"),
    ),
    path(
        "transaction/", include("grab_money.transaction.urls", namespace="transaction")
    ),
    path("currency/", include("grab_money.currency.urls", namespace="currency")),
    path(
        "currency_rate/",
        include("grab_money.currency_rate.urls", namespace="currency_rate"),
    ),
    path(
        "money_statistics/",
        include("grab_money.money_statistics.urls", namespace="money_statistics"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

grab_money/bank_account/urls.py
# Django:
from django.urls import path

# Localfolder:
from . import views

app_name = "bank_account"
urlpatterns = [
    path("", views.account_name_list, name="account-list"),
    path("create/", views.account_name_create, name="add-new-bank_account"),
    path("save/", views.account_name_list),
    path("delete/<int:id>/", views.account_name_delete, name="account-delete"),
    path("edit/<int:id>/", views.account_name_edit, name="bank-account-edit"),
    path("detail/<int:id>/", views.account_detail, name="account-detail"),
]

grab_money/base/urls.py
# Django:
from django.urls import path

# Localfolder:
from . import views

app_name = "base"
urlpatterns = [
    path(
        "upload-transaction-file/",
        views.upload_transaction_file,
        name="upload-transaction-file",
    ),
]

grab_money/category/urls.py
# Django:
from django.urls import path

# Localfolder:
from .views import (
    category_create,
    category_delete,
    category_detail,
    category_edit,
    category_list,
)

app_name = "category"
urlpatterns = [
    path("", category_list, name="category-list"),
    path("create/", category_create, name="category-create"),
    path("edit/<int:id>/", category_edit, name="category-edit"),
    path("delete/<int:id>/", category_delete, name="category-delete"),
    path("detail/<int:id>/", category_detail, name="category-detail"),
]

grab_money/money_statistics/urls.py
# Django:
from django.urls import path

# Localfolder:
from .views import (
    account_credit,
    balance_by_date,
    credit_by_date,
    debit_credit_report,
    debit_credit_report_data,
    statistics,
    transaction_amount,
)

app_name = "money_statistics"
urlpatterns = [
    path("", statistics, name="statistics"),
    path(
        "transaction-amount-chart/", transaction_amount, name="transaction-amount-chart"
    ),
    path("credit-by-date/", credit_by_date, name="credit-by-date"),
    path("account-credit/<int:id>/", account_credit, name="account-credit"),
    path("balance-by-date/", balance_by_date, name="balance-by-date"),
    path("debit-credit-report/", debit_credit_report, name="debit-credit-report"),
    path(
        "debit-credit-report/data",
        debit_credit_report_data,
        name="debit-credit-report-data",
    ),
]

grab_money/users/urls.py
# Django:
from django.urls import path

# Firstparty:
from grab_money.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

grab_money/base/models.py
# Django:
from django.db import models

# Create your models here.

grab_money/money_statistics/models.py
# Django:
from django.db import models

# Create your models here.

grab_money/bank_account/forms.py
# Django:
from django import forms
from django.forms import ModelForm
from django.urls import reverse

# Thirdparty:
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# Firstparty:
from grab_money.bank_account.models import BankAccount


# Create the form class.
class BankAccountForm(ModelForm):
    class Meta:
        model = BankAccount
        fields = [
            "name",
            "number_account",
            "number_card",
            "currency",
            "opening_debit",
            "opening_credit",
            "category",
            "type",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "add-new-bank_account"
        self.helper.form_class = "NewBankAccount"
        self.helper.form_method = "post"
        self.helper.form_action = ""
        self.helper.add_input(Submit("submit", "create"))


class EditBankAccountForm(BankAccountForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_action = reverse(
            "bank_account:bank-account-edit", args=[self.instance.id]
        )
        self.helper.inputs[0].value = "save"

grab_money/currency_rate/forms.py
# Django:
from django import forms
from django.contrib.auth.models import User
from django.urls import reverse

# Thirdparty:
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

# Localfolder:
from .models import CurrencyRate


class CurrencyRateRefreshForm(forms.ModelForm):
    class Meta:
        model = CurrencyRate
        fields = ["date"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "currency-rate-refresh"
        self.helper.form_class = "CurrencyRate"
        self.helper.form_method = "post"
        self.helper.form_action = reverse("currency_rate:currency-rate-refresh")
        self.helper.add_input(Submit("submit", "Refresh"))

grab_money/bank_account/views.py
# Django:
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Firstparty:
from grab_money.bank_account.forms import BankAccountForm, EditBankAccountForm
from grab_money.base.views import universal_error

# Localfolder:
from .models import BankAccount


@login_required(login_url="/accounts/login/")
def account_name_list(request):
    bank_accounts = BankAccount.objects.filter(owner=request.user).order_by("id")
    context = {"bank_accounts": bank_accounts}

    return render(request, "bank_account/list.html", context)


@login_required(login_url="/accounts/login/")
def account_name_create(request):

    base_context = {"bank_account_new": BankAccountForm()}
    if request.method == "GET":
        return render(request, "bank_account/list_edit_new.html", base_context)
    elif request.method == "POST":

        form = BankAccountForm(request.POST)
        if form.is_valid():
            bank_account = form.save(commit=False)
            bank_account.owner = request.user
            bank_account.save()
        return HttpResponseRedirect("/bank_account")
    else:
        return universal_error(request, context={"code": 405})


@login_required(login_url="/accounts/login/")
def account_name_delete(request, id):
    bank_account = BankAccount.objects.get(pk=id)

    if request.user != bank_account.owner:
        return universal_error(request, context={"code": 403})
    bank_account.delete()
    return HttpResponseRedirect("/bank_account")


@login_required(login_url="/accounts/login/")
def account_name_edit(request, id):
    bank_account = BankAccount.objects.get(pk=id)
    form = EditBankAccountForm(instance=bank_account)
    if request.method == "GET":
        return render(request, "bank_account/list_edit.html", context={"form": form})
    elif request.method == "POST":
        if request.user != bank_account.owner:
            return universal_error(request, context={"code": 403})

        form = BankAccountForm(request.POST, instance=bank_account)
        if form.is_valid():
            bank_account = form.save(commit=False)
            bank_account.owner = request.user
            bank_account.save()
        return HttpResponseRedirect("/bank_account")
    else:
        return universal_error(request, context={"code": 405})


@login_required(login_url="/accounts/login/")
def account_detail(request, id):
    try:
        account = BankAccount.objects.get(pk=id)
    except BankAccount.DoesNotExist:
        return universal_error(request, context={"code": 404})

    # Check for right request user
    if account.owner != request.user:
        return universal_error(request, context={"code": 403})

    context = {"account": account}
    return render(request, "bank_account/account_detail.html", context)

grab_money/base/views.py
# Django:
from django.shortcuts import redirect, render

# Localfolder:
from .forms import PARSER_MAPPING, UploadTransactionFileForm


def universal_error(request, context=None):
    # if context is none
    if context is None:
        context = {}
        context["title"] = "Unregistered error"
        context["text"] = "Sorry, we have any problems"
    # if you write any specific context["code"] and ["text"]
    elif "text" in context:
        return render(request, "error.html", context)
    # the most usable errors use by context["code"]
    else:
        if context["code"] == 403:
            context["title"] = "Access denied"
            context["text"] = "You do not have permission for this action"
        elif context["code"] == 404:
            context["title"] = "Page is not found"
            context["text"] = "The requested URL was not found on this server"
        elif context["code"] == 405:
            context["title"] = "Not Allowed"
            context[
                "text"
            ] = "An unsupported HTTP method was used to execute the request"
        elif context["code"] == 500:
            context["title"] = "Server Error"
            context["text"] = "Sorry, something went wrong"

    return render(request, "error.html", context)


def upload_transaction_file(request):
    if request.method == "GET":
        context = dict(form=UploadTransactionFileForm())
        return render(request, "base/upload_transaction_file.html", context)
    elif request.method == "POST":
        form = UploadTransactionFileForm(request.POST)
        if "file" in request.FILES:
            file = request.FILES["file"]
            parser = PARSER_MAPPING[form.data["parser"]]()
            transactions_data = parser.parse(file)
            parser.store_transactions(transactions_data, request.user)
            return redirect("transaction:transaction-list")
        else:
            return universal_error(
                request, context={"code": 500, "text": "Couldn't found file"}
            )
    else:
        return universal_error(request, context={"code": 405})

grab_money/category/views.py
# Django:
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

# Firstparty:
from grab_money.base.views import universal_error
from grab_money.transaction.models import Transaction

# Localfolder:
from .forms import CategoryForm, EditCategoryForm
from .models import Category


@login_required(login_url="/accounts/login/")
def category_list(request):
    categories = Category.objects.filter()
    context = {"categories": categories}
    return render(request, "category/list.html", context)


@login_required(login_url="/accounts/login/")
def category_create(request):
    context = {"form": CategoryForm()}
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            new_category = form.save(commit=False)
            new_category.owner = request.user
            new_category.save()
            return redirect("category:category-list")
    elif request.method == "GET":
        return render(request, "category/category_create.html", context)


@login_required(login_url="/accounts/login/")
def category_edit(request, id):
    category = Category.objects.get(pk=id)
    if request.method == "POST":
        if request.user != category.owner:
            return universal_error(request, context={"code": 403})
        form = EditCategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect("category:category-list")
    else:
        if request.user != category.owner:
            return universal_error(request, context={"code": 403})
        form = EditCategoryForm(instance=category)
    return render(request, "category/category_edit.html", {"form": form})


@login_required(login_url="/accounts/login/")
def category_delete(request, id):
    category = Category.objects.get(pk=id)
    if request.user != category.owner:
        return universal_error(request, context={"code": 403})
    category.delete()
    return redirect("category:category-list")


@login_required(login_url="/accounts/login/")
def category_detail(request, id):
    category = Category.objects.get(pk=id)
    transactions = Transaction.objects.filter(category=id)
    context = {"category": category, "transactions": transactions}
    return render(request, "category/category_detail.html", context)

grab_money/currency/views.py
# Django:
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Localfolder:
from .models import Currency


@login_required(login_url="/accounts/login/")
def currency_list(request):
    currencies = Currency.objects.all()
    context = {"currencies": currencies}
    return render(request, "currency/list.html", context)

grab_money/currency_rate/views.py
# Django:
# Stdlib:
import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

# Firstparty:
from grab_money.currency.models import Currency
from grab_money.currency_rate.utils import get_all_currency_rate_date

# Localfolder:
from .forms import CurrencyRateRefreshForm
from .models import CurrencyRate


@login_required(login_url="/accounts/login/")
def currency_rate_list(request, date):

    currencies = Currency.objects.all()
    if date == "today":
        date = datetime.datetime.now().date()
    rates = CurrencyRate.objects.filter(date=date)

    context = {
        "currencies": currencies,
        "rates": rates,
        "date": date,
        "form": CurrencyRateRefreshForm(),
    }

    return render(request, "currency_rate/list.html", context)


@login_required(login_url="/accounts/login/")
def currency_rate_refresh(request):

    if request.method == "POST":
        form = CurrencyRateRefreshForm(request.POST)

        date = form.data["date"]
        rates = get_all_currency_rate_date(date)

        for rate in rates:
            try:
                currency = Currency.objects.get(short_unit_label=rate["abbreviation"])
                if not CurrencyRate.objects.filter(
                    date=date, currency_id=currency
                ).exists():
                    new_rate = CurrencyRate()
                    new_rate.currency_id = currency
                    new_rate.rate = rate["rate"]
                    new_rate.date = date
                    new_rate.scale = rate["scale"]
                    new_rate.save()

            except Currency.DoesNotExist:
                pass

    return redirect("currency_rate:currency-rate-list", date=date)


@login_required(login_url="/accounts/login/")
def currency_rate_detail(request, shortalias):
    currencies = Currency.objects.filter(short_unit_label=shortalias)
    if currencies:
        currency = currencies[0]
        rates = CurrencyRate.objects.filter(currency_id=currency)
        context = {
            "currency": currency,
            "rates": rates,
            "scale": rates and rates[0].scale or False,
        }
        return render(request, "currency_rate/detail.html", context)
    return currency_rate_list(request)

grab_money/templates/bank_account/account_detail.html
{% extends "base.html" %}
{% load static %}

{% block additional_javascript %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="{% static 'js/account_credit.js' %}"></script>
{% endblock %}

{% block title %} Account Detail {% endblock %}
{% block content %}

    <h3>Account '{{ account.name }}' overview</h3>
    <div class="btn-group" style="margin-top: 50px;">
            <a href="{% url 'bank_account:bank-account-edit' account.id %}" class="btn btn-info"><i class="fas fa-edit" aria-hidden="true" style="margin-right: 10px;"></i>
                Edit
            </a>
            <a href="{% url 'bank_account:account-delete' account.id %}" class="btn btn-info"><i class="fas fa-trash" style="margin-right: 10px;"></i>
                Delete
            </a>
      </div>

      <div style="font-size: 18px; margin-top: 0px;">
        <ul class="list-group list-group-flush">
            <li class="list-group-item" style="white-space: pre-wrap;"></li>
            <li class="list-group-item" style="white-space: pre-wrap;">Name:                {{ account.name }}</li>
            <li class="list-group-item" style="white-space: pre-wrap;">Balance:            {{ account.balance }}</li>
            <li class="list-group-item" style="white-space: pre-wrap;">Currency:           {{ account.currency }}</li>
            <li class="list-group-item" style="white-space: pre-wrap;">Type:                  {{ account.type }}</li>
            <li class="list-group-item" style="white-space: pre-wrap;">Category:           {{ account.category }}</li>
            <li class="list-group-item" style="padding-bottom: 0px;">Transaction amount chart graph:
                <div id="container" style="width: 50%; margin-top: 25px;">
                    <canvas id="account-credit" data-url="{% url 'money_statistics:account-credit' account.id %}"></canvas>
                </div>

            </li>

          </ul>
      </div>

{% endblock %}

grab_money/templates/bank_account/list.html
{% extends "base.html" %}

{% block title %} Bank Account {% endblock %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<style>
.flex-container {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: center;
}

.flex-container > div {
  width: 300px;
  margin: 10px;
  text-align: center;
  line-height: 75px;
  font-size: 30px;
}

</style>
</head>
<h3>Bank accounts <a class="btn btn-info" href="{% url 'bank_account:add-new-bank_account' %}" style="margin-left:20px;">
    <i class="fas fa-plus" aria-hidden="true"></i>
    Add new
    </a>
</h3>
<body>
    <div class="flex-container">
        {% for item in bank_accounts %}
        <div class="flex-container border-info rounded alert shadow-lg p-3 hover-effect1">
                <a href="{% url 'bank_account:account-detail' item.id %}" style="color: black; padding: 20px;">
                    <h4 class="text-break" >{{item.name}}</h4>
                </a>
                <div style="align-self: flex-end;">
                <h5> Ballance: {{ item.balance}} {{item.currency.short_unit_label}}</h5>
                </div>

                <div class="btn-group"  style="margin-left: 100px; margin-top: 50px; align-self: flex-end;">
                <a href="{% url 'bank_account:bank-account-edit' item.id %}" class="btn btn-info">
                    <i class="fas fa-edit" aria-hidden="true"></i>Edit
                </a>
                <a href="{% url 'bank_account:account-delete' item.id %}" class="btn btn-info"><i class="fas fa-trash"></i>
                Delete
                </a>
                </div>
        </div>
        {% endfor %}
    </div>

</body>
</html>

{% endblock %}

grab_money/templates/bank_account/list_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Bank Account{% endblock %}

{% block content %}
    {% if bank_account %}
        <div class="alert alert-{{bank_account_type}}" role="alert">

        </div>
    {% endif %}
    {% crispy form form.helper %}

{% endblock %}

grab_money/templates/bank_account/list_edit_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Add New Bank Account {% endblock %}

{% block content %}
{% crispy bank_account_new bank_account_new.helper %}

{% endblock %}